# Generated by Django 5.0 on 2023-12-21 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cursos", "0003_producto_contenido_alter_categoriaprod_updated_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="contenido",
            field=models.CharField(default="descripcion del curso", max_length=100),
        ),
    ]
