# Generated by Django 4.2.5 on 2023-10-17 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_alter_cursos_imagen'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cursos',
            new_name='Curso',
        ),
    ]
