# Generated by Django 4.2.5 on 2023-10-17 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_rename_cursos_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='contenido',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
